token_user_search: sub
check_scope: true
cors:
  enabled: true
  allow_origin:
    - "*"
  methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  headers:
    - "Accept"
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  max_age: 86400
plugins:
  test:
    uri: postgres://postgres:root@localhost:5433/easyrestdb?maxOpenConns=100&maxIdleConns=25&connMaxLifetime=5&connMaxIdleTime=10&timeout=30&bulkThreshold=100&sslmode=disable&search_path=public
    path: ./easyrest-plugin-postgres
    enable_cache: true
